language: python
sudo: false
addons:
  apt:
    packages:
     - python-pip
dist: trusty

install:
 - gem install kramdown-rfc2629
 - pip install xml2rfc

script: make ghpages

env:
 global:
 - secure: "Im9OMgqGzhrWGvSyaJ3W0/xRjhl39Ylt4ANKP80HznQ9qCsbAUb31BaCv9K9lsmT4gPLMU5e1Gwtsmy1MK6TpBHQVIDluWIdo6wWiNqfY335TOw7ASTVPQGSXDgw1tx3fhNDxTC7wLqIi6muvfHaxWwWG/weXUtkpEyezfyQ2dI="
